### ISSUE TITLE
Standardization - tracking issue

### ISSUE THREAD

**Issue by AntoniosBarotsis** [resend/resend-rs#3]
List of things that need to be done to bring this crate up to spec with [`resend-node`](https://github.com/resend/resend-node).

## Lib
- [x] Rename everything to match `resend-node`
- [x] Restructure the modules to follow `resend-node` (for example the `batch` module)
- [x] User agent should not be editable by users
- [x] cross check if optionals are used correctly (between `resend-node` and API docs)
- [x] Fix the `email.retrieve` null bug ([see example return](https://resend.com/docs/api-reference/emails/retrieve-email))
- [X] Handle rate limits 

## Other
- [x] Improve/update docs in the docs.rs homepage (also mention any other needed dependencies such as tokio)
- [x] Update changelog
- [x] Change license to MIT (oops)
- [x] Check for breaking changes in CI
- [x] Make sure no links are pointing to the old repo url
- [x] Fix outdated links in rustdoc comments
- [ ] Update the README (link to the official docs when those are merged)
